#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d WWW DEV SYS DOC GFX MUS VID

bspc config border_width         4
bspc config window_gap           6

bspc config normal_border_color "#40318D"
bspc config active_border_color "#40318D"
bspc config focused_border_color "#BFCE72"
bspc config presel_feedback_color "#7869C4"

override-redirect = true
wm-restack = bspwm

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a galculator state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#AutoStart
polybar
